---
new_page_extension: md
auto_deploy: false
admin_path: "public/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: censorship
  label: Censorship
  create: all
  match: "**/*"
- type: directory
  path: content/boobs+
  label: Boobs+
  create: all
  match: "**/*"
- type: directory
  path: content/images
  label: Images
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D --port 1313
version: 0.79.0
